name: Deploy to AWS EC2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run:  pytest
  
  
